config/routes.rb
Rails.application.routes.draw do
  get 'affirmations/index'
  get 'affirmations/new'
  get 'affirmations/create'
  get 'affirmations/show'
  get 'affirmations/edit'
  get 'affirmations/update'
  get 'affirmations/destroy'
  get 'motivations/index'
  get 'motivations/show'
  get 'meditations/index'
  get 'audio/index'
  get 'audio/show'
  get 'video/index'
  get 'video/show'
  get 'story/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :affirmations, only: [:index, :show, :new, :update, :create, :update, :destroy]
  resources :motivations, only: [:index, :show] 
  resources :meditations, only: [:index, :show]
  resources :video, only: [:index, :show]
  resources :audio, only: [:index, :show]
  resources :stories, only: [:index, :show]
  
  root 'affirmations#index'
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
    validates :title, presence: true,
                    length: { minimum: 5 }

                    has_rich_text :text
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
    validates :name, presence: true,
    length: { minimum: 5 }
end

app/models/meditation.rb
class Meditation < ApplicationRecord
end

app/models/motivation.rb
class Motivation < ApplicationRecord
    
end

app/models/video.rb
class Video < ApplicationRecord
    has_one_attached :clip
    has_many_attached :thumbnail
 
end

app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController
  def index
    @affirmations = Affirmation.all
  end

  def show
    @affirmation = Affirmation.find(params[:id])
  end
 
  def new
    @affirmation = Affirmation.new
  end

  def create
    #render plain: params[:article].inspect
    @affirmation = Affirmation.new(Affirmation_params)
    @affirmation.save
    redirect_to affirmation_show(@affirmation)


  def edit
    @affirmation = Affirmation.find(params[:id])
  end
  
  if @affirmation.save
    redirect_to @affirmation
  else
    render 'new'
  end
end
 
def update
  @affirmation = Affirmation.find(params[:id])
 
  if @affirmation.update(affirmaiton_params)
    redirect_to @affirmation
  else
    render 'edit'
  end
end
 
private
  def affirmation_params
    params.require(:affirmation).permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audio_controller.rb
class AudioController < ApplicationController
    def index
        @audio = Audio.all
      end

      def show
      end
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController

    def index
        @meditations = Meditation.all
      end

      def show
      end
      
end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController

    def index
        @motivations = Motivation.order(:name)
    end

    def show 
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    def index
    end
     
    def show
    end
    
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
    before_action :set_video, only: [:index, :show]

    def index
        @videos = Video.all
    end

    def show
    end

    private

    def set_video
        
        @video = Video.find(params[:id])
    end

    def video_params
        params.require(:video).permit(:title, :description,  :name, :clip, :thumbnail)
    end
end

app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/meditations_helper.rb
module MeditationsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/affirmations/index.html.erb
<h1>Affirmations</h1>
 


<table>
<tr> 
  <% @affirmations.each do |affirmation| %>
      <td><%= affirmation.text %></td>
      <td><button><%= link_to 'New', affirmation_new_path %></button></td>
      <td><%= link_to 'Show', affirmation_show_path %></td>
      <td><button type="button" class="btn btn-primary"><%= link_to 'New Affirmation', new_affirmation_path %></button></td>
    </tr>
  <% end %>
</table>

app/views/affirmations/new.html.erb
<h1>Daily Affirmation</h1>


<%= form_with scope: :affirmation, url: affirmations_index_path, local: true do |form| %>
 
    <% if @affirmation.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@affirmation.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @affirmation.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
   
  <%= link_to 'Back', affirmations_index_path %>

app/views/affirmations/show.html.erb
<p>
<strong>Text:</strong>
<%= @affirmation.text %>
</p>

app/views/audio/index.html.erb
<h1>Audio Lessons</h1>


<div class="container .col-lg-1">
<button class="mt btn btn-lg btn-primary z-depth-2"><%= link_to 'Audio Lesson', audio_index_path %></button>
</div>

app/views/audio/show.html.erb
<h1>Audio Lessons</h1>

<button class="container btn btn-primary">
<%= link_to "Podcast", "https://soundcloud.com/untangle" =%></button>

<ul>
    <li>
        <%= link_to "Audio Lessons", audio_index_path %>
    </li>
</ul>

app/views/meditations/index.html.erb
<h1 class="container .col-md-5">Meditations</h1>

app/views/motivations/index.html.erb
<h1> Motivations </h1>



<div class="container .col-sm-6 motivations">
    <ul>
        <button type="button" class="btn btn-primary"><li>Title</li>
        <li>Description</li>
        <li>Author</li>
    </ul>
</div>

app/views/stories/index.html.erb
<h1>Story TIme</h1>

<button type="button" class="btn btn-primary">Story Link goes here</button>

app/views/video/_form.html.erb
<%= form_tag '', id: 'video_pre_upload' do %>
    <div class="form-group">
      <%= text_field_tag :title, @pre_upload_info[:title], required: true,
                         placeholder: 'Title', class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= text_area_tag :description, @pre_upload_info[:description], required: true,
                        placeholder: 'Description', class: 'form-control' %>
    </div>
  <% end %>
  
  <%= form_tag '', id: 'video_upload', multipart: true do %>
    <%= hidden_field_tag :token, '' %>
  
    <div class="form-group">
      <%= file_field_tag :file, required: true %>
    </div>
  <% end %>
  
  <button id="submit_pre_upload_form" class="btn btn-lg btn-primary">Upload</button>
  <%= image_tag 'ajax-loader.gif', class: 'preloader', alt: 'Uploading...', title: 'Uploading...' %>

app/views/video/_youtube.html.erb
#!/usr/bin/ruby

require 'rubygems'
gem 'google-api-client', '>0.7'
require 'google/api_client'
require 'trollop'

# Set DEVELOPER_KEY to the API key value from the APIs & auth > Credentials
# tab of
# {{ Google Cloud Console }} <{{ https://cloud.google.com/console }}>
# Please ensure that you have enabled the YouTube Data API for your project.
DEVELOPER_KEY = 'REPLACE_ME'
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'

def get_service
  client = Google::APIClient.new(
    :key => DEVELOPER_KEY,
    :authorization => nil,
    :application_name => $PROGRAM_NAME,
    :application_version => '1.0.0'
  )
  youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

  return client, youtube
end

def main
  opts = Trollop::options do
    opt :q, 'Search term', :type => String, :default => 'Google'
    opt :max_results, 'Max results', :type => :int, :default => 25
  end

  client, youtube = get_service

  begin
    # Call the search.list method to retrieve results matching the specified
    # query term.
    search_response = client.execute!(
      :api_method => youtube.search.list,
      :parameters => {
        :part => 'snippet',
        :q => opts[:q],
        :maxResults => opts[:max_results]
      }
    )

    videos = []
    channels = []
    playlists = []

    # Add each result to the appropriate list, and then display the lists of
    # matching videos, channels, and playlists.
    search_response.data.items.each do |search_result|
      case search_result.id.kind
        when 'youtube#video'
          videos << "#{search_result.snippet.title} (#{search_result.id.videoId})"
        when 'youtube#channel'
          channels << "#{search_result.snippet.title} (#{search_result.id.channelId})"
        when 'youtube#playlist'
          playlists << "#{search_result.snippet.title} (#{search_result.id.playlistId})"
      end
    end

    puts "Videos:\n", videos, "\n"
    puts "Channels:\n", channels, "\n"
    puts "Playlists:\n", playlists, "\n"
  rescue Google::APIClient::TransmissionError => e
    puts e.result.body
  end
end

app/views/video/index.html.erb
<h1>Videos</h1>


<%= form_for([@video]) %>
<button type="button" class=""btn btn-primary"><%= link_to "Videos", video_show_path %></button>

app/views/video/show.html.erb
<h1>Video</h1>

<%= render :partial => 'video/youtube' %>
<p id="notice"></p>
<%= video.title %>
<link href="https://vjs.zencdn.net/7.0.3/video-js.css" rel="stylesheet">

<script src="https://vjs.zencdn.net/ie8/ie8-version/video.js-ie8.min.js"><script>

<p>
    <strong>Title:</strong>
    <%= video.title %>
</p>
<div style="width:400px; height:400px;">
<%= image_tag(@video.thumbnail, style: 'width:100%;height:auto') %>
</div>

<div style="width:400px; height:400px;">
<%= video_tag(url_for @video.clip, style: 'width:100%;height:auto', controls: " " ) %>
</div>

<video id="my-video" class="video-js" controls preload=
"auto" width="640" height="264" poster="<%= url_for(@video.thumbnail) %>"
data-setup="{}">
<source src="<%= url_for(@video.clip) %>"" type="video/mp4" />
</video>

<p>
<strong>Description:</strong>
<%= @video.description %>
</p>

<%= link_to "Back", video_index_path %>
<%= link_to "Home", affirmations_index_path %>

<script src="https://vjs.zencdn.net/7.6.6/video.js"></script>