config/routes.rb
Rails.application.routes.draw do
  get 'affirmations/index'
  get 'affirmations/new'
  get 'affirmations/create'
  get 'affirmations/show'
  get 'affirmations/edit'
  get 'affirmations/update'
  get 'affirmations/destroy'
  get 'motivations/index'
  get 'motivations/show'
  get 'meditations/index'
  get 'audio/index'
  get 'audio/show'
  get 'video/index'
  get 'video/show'
  get 'story/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :affirmations, only: [:index, :show, :new, :update, :create, :update, :destroy]
  resources :motivations, only: [:index, :show] 
  resources :meditations, only: [:index, :show]
  resources :video, only: [:index, :show]
  resources :audio, only: [:index, :show]
  resources :stories, only: [:index, :show]
  
  root 'affirmations#index'
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
    validates :title, presence: true,
                    length: { minimum: 5 }

                    has_rich_text :text
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
    validates :name, presence: true,
    length: { minimum: 5 }
end

app/models/meditation.rb
class Meditation < ApplicationRecord
end

app/models/motivation.rb
class Motivation < ApplicationRecord
    
end

app/models/video.rb
class Video < ApplicationRecord
    has_one_attached :clip
    has_many_attached :thumbnail
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audio_controller.rb
class AudioController < ApplicationController
    def index
        @audio = Audio.all
      end

      def show
      end
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController

    def index
        @meditations = Meditation.all
      end

      def show
      end
      
end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController

    def index
        @motivations = Motivation.order(:name)
    end

    def show 
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    def index
    end
     
    def show
    end
    
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
    before_action :set_video, only: [:index, :show]

    def index
        @videos = Video.all
    end

    def show
    end

    private

    def set_video
        
        @video = Video.find(params[:id])
    end

    def video_params
        params.require(:video).permit(:title, :description,  :name, :clip, :thumbnail)
    end
end

app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/meditations_helper.rb
module MeditationsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_buttons.html.erb
<table>

    <tr class="container-md buttons">
      <td class="container-1"><button type="button" class="btn btn-warning"><%= link_to 'Meditations', meditations_index_path %></button></td>
      <td class="container-2"><button type="button" class="btn btn-warning"><%= link_to 'Affirmations', affirmations_index_path %></button></td>
      <td class="container-3"><button type="button" class="btn btn-warning"><%= link_to 'Motivations', motivations_index_path %></button></td>
      <td class="container-4"><button type="button" class="btn btn-warning"><%= link_to 'Audio Lessons', audio_index_path %></button></td>
      <td class="container-5"><button type="button" class="btn btn-warning"><%= link_to 'Story Time', story_index_path %></button></td>
      <td class="container-7"><button type="button" class="btn btn-warning"><%= link_to 'Video', video_index_path %></button></td>
    </tr>

</table>

app/views/layouts/_footer.html.erb
<div class="container">
  </footer class="footer">
    <small>Copyright &copy Black Words Matter </small>
    <nav>
    <%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "mouse-pointer" %>
        <% end %>
      
      <%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "shopping-cart" %>
        <% end %>
      
      <%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "calendar" %>
        <% end %>
      
      <%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "users" %>
        <% end %>
      
      
      
    </nav>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">About<%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "users" %>
        <% end %></h5>
      <%= button_tag type: :submit, class: "btn btn-primary" do %>
        <%= fa_icon "users" %>
        <% end %>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Affirmations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
  </head>

  <body>
  <h1 class="page-title">Black <span style="color:gold;">Words</span> Matter</h1>
  <%= render :partial => 'layouts/navbar' %>
  <%= render :partial => 'layouts/buttons' %>
  
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>
  </body>
</html>